# configure updates globally
# default: all
# allowed: all, insecure, False
update: insecure

# configure dependency pinning globally
# default: True
# allowed: True, False
pin: False

# update schedule
# default: empty
# allowed: "every day", "every week", ..
schedule: "every week"
